// Auto-generated by scripts/generate-skills.ts — do not edit manually

export interface Category {
  code: string;
  slug: string;   // actual directory name e.g. "01-model-architecture"
  label: string;
  description: string;
}

export const CATEGORIES: Category[] = [
  {
    code: "00",
    slug: "0-autoresearch-skill",
    label: "Autoresearch",
    description: "Orchestrates end-to-end autonomous AI research projects using a two-loop architecture. The inner loop runs rapid experiment iterations with clear optimization targets. The outer loop synthesizes results, identifies patterns, and steers research direction. Routes to domain-specific skills for execution, supports continuous agent operation via Claude Code /loop and OpenClaw heartbeat, and produces research presentations and papers. Use when starting a research project, running autonomous experiments, or managing a multi-hypothesis research effort.",
  },
  {
    code: "01",
    slug: "01-model-architecture",
    label: "Model Architecture",
    description: "Implements and trains LLMs using Lightning AI's LitGPT with 20+ pretrained architectures (Llama, Gemma, Phi, Qwen, Mistral).",
  },
  {
    code: "02",
    slug: "02-tokenization",
    label: "Tokenization",
    description: "Fast tokenizers optimized for research and production.",
  },
  {
    code: "03",
    slug: "03-fine-tuning",
    label: "Fine Tuning",
    description: "Expert guidance for fine-tuning LLMs with Axolotl - YAML configs, 100+ models, LoRA/QLoRA, DPO/KTO/ORPO/GRPO, multimodal support.",
  },
  {
    code: "04",
    slug: "04-mechanistic-interpretability",
    label: "Mechanistic Interpretability",
    description: "Provides guidance for interpreting and manipulating neural network internals using nnsight with optional NDIF remote execution.",
  },
  {
    code: "05",
    slug: "05-data-processing",
    label: "Data Processing",
    description: "GPU-accelerated data curation for LLM training.",
  },
  {
    code: "06",
    slug: "06-post-training",
    label: "Post Training",
    description: "Expert guidance for GRPO/RL fine-tuning with TRL for reasoning and task-specific model training.",
  },
  {
    code: "07",
    slug: "07-safety-alignment",
    label: "Safety Alignment",
    description: "Anthropic's method for training harmless AI through self-improvement.",
  },
  {
    code: "08",
    slug: "08-distributed-training",
    label: "Distributed Training",
    description: "Simplest distributed training API.",
  },
  {
    code: "09",
    slug: "09-infrastructure",
    label: "Infrastructure",
    description: "Reserved and on-demand GPU cloud instances for ML training and inference.",
  },
  {
    code: "10",
    slug: "10-optimization",
    label: "Optimization",
    description: "Activation-aware weight quantization for 4-bit LLM compression with 3x speedup and minimal accuracy loss.",
  },
  {
    code: "11",
    slug: "11-evaluation",
    label: "Evaluation",
    description: "Evaluates code generation models across HumanEval, MBPP, MultiPL-E, and 15+ benchmarks with pass@k metrics.",
  },
  {
    code: "12",
    slug: "12-inference-serving",
    label: "Inference Serving",
    description: "Runs LLM inference on CPU, Apple Silicon, and consumer GPUs without NVIDIA hardware.",
  },
  {
    code: "13",
    slug: "13-mlops",
    label: "MLOps",
    description: "Track ML experiments, manage model registry with versioning, deploy models to production, and reproduce experiments with MLflow - framework-agnostic ML lifecycle platform.",
  },
  {
    code: "14",
    slug: "14-agents",
    label: "Agents",
    description: "Provides guidance for automatically evolving and optimizing AI agents across any domain using LLM-driven evolution algorithms.",
  },
  {
    code: "15",
    slug: "15-rag",
    label: "RAG",
    description: "Open-source embedding database for AI applications.",
  },
  {
    code: "16",
    slug: "16-prompt-engineering",
    label: "Prompt Engineering",
    description: "Build complex AI systems with declarative programming, optimize prompts automatically, create modular RAG systems and agents with DSPy - Stanford NLP's framework for systematic LM programming.",
  },
  {
    code: "17",
    slug: "17-observability",
    label: "Observability",
    description: "LLM observability platform for tracing, evaluation, and monitoring.",
  },
  {
    code: "18",
    slug: "18-multimodal",
    label: "Multimodal",
    description: "PyTorch library for audio, image, and video generation including text-to-music (MusicGen) and text-to-sound (AudioGen).",
  },
  {
    code: "19",
    slug: "19-emerging-techniques",
    label: "Emerging Techniques",
    description: "Compress large language models using knowledge distillation from teacher to student models.",
  },
  {
    code: "20",
    slug: "20-ml-paper-writing",
    label: "ML Paper Writing",
    description: "Generates publication-quality figures for ML papers from research context.",
  },
  {
    code: "21",
    slug: "21-research-ideation",
    label: "Research Ideation",
    description: "Guides researchers through structured ideation frameworks to discover high-impact research directions.",
  },
  {
    code: "22",
    slug: "22-agent-native-research-artifact",
    label: "Agent Native Research Artifact",
    description: "Compiles any research input — PDF papers, GitHub repositories, experiment logs, code directories, or raw notes — into a complete Agent-Native Research Artifact (ARA) with cognitive layer (claims, concepts, heuristics), physical layer (configs, code stubs), exploration graph, and grounded evidence.",
  },
];

export const TOTAL_SKILLS = 98;
export const TOTAL_CATEGORIES = 23;
