// scripts/generate-skills.ts
// Run: npx ts-node --skip-project scripts/generate-skills.ts
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPO_ROOT = path.resolve(__dirname, "../../_skills-source");
const OUT_SKILLS = path.resolve(__dirname, "../lib/skills.ts");
const OUT_CATEGORIES = path.resolve(__dirname, "../lib/categories.ts");

// Dirs to skip (not skill categories)
const SKIP_DIRS = new Set([
  "anthropic_official_docs",
  "demos",
  "dev_data",
  "docs",
  "packages",
  "video-promo",
  ".github",
  ".claude-plugin",
]);

function parseFrontmatter(content: string): { name?: string; description?: string } {
  // Normalize line endings (handle CRLF from Windows git clone)
  const normalized = content.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const match = normalized.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const block = match[1];
  const name = block.match(/^name:\s*(.+)$/m)?.[1]?.trim();
  const description = block.match(/^description:\s*(.+)$/m)?.[1]?.trim();
  return { name, description };
}

function toLabel(dirName: string): string {
  // "01-model-architecture" → "Model Architecture"
  // "0-autoresearch-skill" → "Autoresearch"
  const withoutNum = dirName.replace(/^\d+-/, "");
  return withoutNum
    .replace(/-skill$/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function toCategorySlug(dirName: string): string {
  // Keep dir name as-is for githubPath accuracy
  return dirName;
}

interface SkillEntry {
  slug: string;
  name: string;
  description: string;
  categoryCode: string;
  categorySlug: string; // actual dir name e.g. "01-model-architecture"
  githubPath: string;
}

interface CategoryEntry {
  code: string;
  dirName: string;
  label: string;
  description: string;
}

function main() {
  const allDirs = fs
    .readdirSync(REPO_ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !SKIP_DIRS.has(d.name) && /^\d/.test(d.name))
    .map((d) => d.name)
    .sort();

  const categories: CategoryEntry[] = [];
  const skills: SkillEntry[] = [];

  for (let idx = 0; idx < allDirs.length; idx++) {
    const dirName = allDirs[idx];
    const code = String(idx).padStart(2, "0");
    const dirPath = path.join(REPO_ROOT, dirName);
    const label = toLabel(dirName);

    // Check if this category has SKILL.md directly (e.g. autoresearch)
    const directSkillMd = path.join(dirPath, "SKILL.md");

    if (fs.existsSync(directSkillMd)) {
      // Single-skill category
      const content = fs.readFileSync(directSkillMd, "utf-8");
      const { name, description } = parseFrontmatter(content);
      if (!name || !description) {
        console.warn(`WARN: missing frontmatter in ${directSkillMd}`);
        continue;
      }
      const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
      categories.push({ code, dirName, label, description });
      skills.push({
        slug,
        name,
        description,
        categoryCode: code,
        categorySlug: dirName,
        githubPath: `${dirName}/SKILL.md`,
      });
    } else {
      // Multi-skill category — subdirectories
      const subDirs = fs
        .readdirSync(dirPath, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort();

      let categoryDescription = label + " skills";

      for (const skillDirName of subDirs) {
        const skillMdPath = path.join(dirPath, skillDirName, "SKILL.md");
        if (!fs.existsSync(skillMdPath)) continue;
        const content = fs.readFileSync(skillMdPath, "utf-8");
        const { name, description } = parseFrontmatter(content);
        if (!name || !description) {
          console.warn(`WARN: missing frontmatter in ${skillMdPath}`);
          continue;
        }
        // Use first skill description as category description
        if (categoryDescription === label + " skills") {
          categoryDescription = description.split(".")[0] + ".";
        }
        skills.push({
          slug: skillDirName,
          name,
          description,
          categoryCode: code,
          categorySlug: dirName,
          githubPath: `${dirName}/${skillDirName}/SKILL.md`,
        });
      }

      categories.push({ code, dirName, label, description: categoryDescription });
    }
  }

  // Write skills.ts
  const skillLines: string[] = [
    `// Auto-generated by scripts/generate-skills.ts — do not edit manually`,
    `// Source: https://github.com/Demerzels-lab/Aires-Research-Agent`,
    ``,
    `export interface Skill {`,
    `  slug: string;`,
    `  name: string;`,
    `  description: string;`,
    `  categoryCode: string;`,
    `  categorySlug: string;`,
    `  githubPath: string;`,
    `}`,
    ``,
    `export const SKILLS: Skill[] = [`,
  ];

  for (const s of skills) {
    skillLines.push(`  {`);
    skillLines.push(`    slug: ${JSON.stringify(s.slug)},`);
    skillLines.push(`    name: ${JSON.stringify(s.name)},`);
    skillLines.push(`    description: ${JSON.stringify(s.description)},`);
    skillLines.push(`    categoryCode: ${JSON.stringify(s.categoryCode)},`);
    skillLines.push(`    categorySlug: ${JSON.stringify(s.categorySlug)},`);
    skillLines.push(`    githubPath: ${JSON.stringify(s.githubPath)},`);
    skillLines.push(`  },`);
  }

  skillLines.push(`];`, ``);
  skillLines.push(`export function getSkillsByCategory(code: string): Skill[] {`);
  skillLines.push(`  return SKILLS.filter((s) => s.categoryCode === code);`);
  skillLines.push(`}`, ``);
  skillLines.push(`export function getSkillBySlug(slug: string): Skill | undefined {`);
  skillLines.push(`  return SKILLS.find((s) => s.slug === slug);`);
  skillLines.push(`}`, ``);

  fs.writeFileSync(OUT_SKILLS, skillLines.join("\n"), "utf-8");
  console.log(`✓ Generated ${skills.length} skills → lib/skills.ts`);

  // Write categories.ts
  const catLines: string[] = [
    `// Auto-generated by scripts/generate-skills.ts — do not edit manually`,
    ``,
    `export interface Category {`,
    `  code: string;`,
    `  slug: string;   // actual directory name e.g. "01-model-architecture"`,
    `  label: string;`,
    `  description: string;`,
    `}`,
    ``,
    `export const CATEGORIES: Category[] = [`,
  ];

  for (const c of categories) {
    catLines.push(`  {`);
    catLines.push(`    code: ${JSON.stringify(c.code)},`);
    catLines.push(`    slug: ${JSON.stringify(c.dirName)},`);
    catLines.push(`    label: ${JSON.stringify(c.label)},`);
    catLines.push(`    description: ${JSON.stringify(c.description)},`);
    catLines.push(`  },`);
  }

  catLines.push(`];`, ``);
  catLines.push(`export const TOTAL_SKILLS = ${skills.length};`);
  catLines.push(`export const TOTAL_CATEGORIES = ${categories.length};`);
  catLines.push(``);

  fs.writeFileSync(OUT_CATEGORIES, catLines.join("\n"), "utf-8");
  console.log(`✓ Generated ${categories.length} categories → lib/categories.ts`);
}

main();
